theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true
scrolloff = 8
bufferline = "multiple"
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
